- platform: generic
  stream_source: rtsp://admin:@192.168.86.45:554/
  still_image_url: http://admin@192.168.86.45:554/snapshot
  name: garage

- platform: generic
  stream_source: rtsp://admin@192.168.86.47:554/
  still_image_url: http://admin:@192.168.86.47:554/snapshot
  name: lounge

- platform: generic
  stream_source: rtsp://admin@192.168.86.48:554/
  still_image_url: http://admin:@192.168.86.48:554/snapshot
  name: yurt

- platform: generic
  stream_source: rtsp://admin:@192.168.86.250:554/
  still_image_url: http://admin@192.168.86.250:554/snapshot
  name: dining

# - platform: generic
#   stream_source: rtsp://jaw:cadbury@192.168.86.246:8080/h264_ulaw.sdp
#   still_image_url: http://jaw:cadbury@192.168.86.246:8080/snapshot
#   name: stove_ulaw

# - platform: onvif
#   host: 192.168.86.246

# ================
# Third-party
# ================

- platform: bom
  name: Sydney
  location: Sydney

