# - platform: generic
#   name: Living Room
#   username: !secret camera_username
#   password: !secret alnum
#   still_image_url: http://camera3796.local:3796/snapshot.cgi

# - platform: generic
#   name: Basement Storage
#   username: !secret camera_username
#   password: !secret alnum
#   still_image_url: http://camera3797.local:3797/snapshot.cgi

# - platform: generic
#   name: Garage
#   username: !secret camera_username
#   password: !secret alnum
#   still_image_url: http://camera3798.local:3698/snapshot.cgi

- platform: generic
  stream_source: rtsp://192.168.86.47:554/
  still_image_url: http://192.168.86.47:554/snapshot
  name: lounge

- platform: generic
  stream_source: rtsp://192.168.86.48:554/
  still_image_url: http://192.168.86.48:554/snapshot
  name: yurt

- platform: generic
  stream_source: rtsp://192.168.86.45:554/
  still_image_url: http://192.168.86.45:554/snapshot
  name: garage

- platform: generic
  stream_source: rtsp://192.168.86.49:554/
  still_image_url: http://192.168.86.49:554/snapshot
  name: outside

# ================
# Third-party
# ================

- platform: bom
  name: Sydney
  location: Sydney

