# ================
# Air conditioners
# ================

- platform: generic_thermostat
  name: Kirwin Aircon
  heater: switch.kirwin_aircon_relay
  target_sensor: sensor.rumpus_temperature
  ac_mode: true
  min_temp: 20
  max_temp: 24
  target_temp: 22
  cold_tolerance: 2.0
  hot_tolerance: 1.0
  precision: 0.1

- platform: generic_thermostat
  name: Chianti Aircon
  heater: switch.chianti_aircon_relay
  target_sensor: sensor.upstairs_attic_temperature
  ac_mode: true
  min_temp: 20
  max_temp: 24
  target_temp: 22
  cold_tolerance: 2.0
  hot_tolerance: 1.0
  precision: 0.1

# ================
# Beer warmers
# ================

- platform: generic_thermostat
  name: Beer
  heater: switch.beer_warmer_relay
  target_sensor: sensor.beer_temperature
  ac_mode: false
  min_temp: 16
  max_temp: 22
  target_temp: 19
  cold_tolerance: 1.0
  hot_tolerance: 0.5
  precision: 0.1

- platform: generic_thermostat
  name: Lager
  heater: switch.beer_belt_warmer_relay
  target_sensor: sensor.lager_temperature
  ac_mode: false
  min_temp: 16
  max_temp: 24
  target_temp: 22
  cold_tolerance: 1.0
  hot_tolerance: 0.5
  precision: 0.1

# ================
# Heaters
# ================

- platform: generic_thermostat
  name: Bedroom Heating Panel
  heater: switch.bedroom_heating_panel_relay
  target_sensor: sensor.bedroom_temperature
  ac_mode: false
  min_temp: 14
  max_temp: 22
  target_temp: 18
  cold_tolerance: 2.0
  hot_tolerance: 2.0
  precision: 0.1

# ================
# Dehumidifiers
# ================

- platform: generic_thermostat
  name: Dehumidifier
  heater: switch.dehumidifier_relay
  target_sensor: sensor.mould_degrees
  ac_mode: true
  min_temp: 0
  max_temp: 100
  target_temp: 65
  cold_tolerance: 5.0
  hot_tolerance: 10.0
  precision: 1.0
