# ================
# Core
# ================

homeassistant:
  customize: !include customize.yaml
  media_dirs:
    motion: /media/Movies
    music: /media/Music

default_config:

frontend:
  themes: !include_dir_merge_named themes

hacs:
  token: !secret my_github_hacs_token
  sidepanel_title: Community Store

# Different ways of splitting code at
# https://www.home-assistant.io/docs/configuration/splitting_configuration/#advanced-usage
automation: !include_dir_merge_list automations
group: !include groups.yaml
logbook: !include logbook.yaml
# https://www.home-assistant.io/integrations/logger/#log-levels
logger:
  default: info
history: !include history.yaml
notify: !include notifications.yaml
recorder: !include recorder.yaml
#alert: !include alerts.yaml
#script: !include scripts.yaml


# ================
# Geolocation
# ================

person: !include person.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml

#owntracks:

geo_location:
  - platform: nsw_rural_fire_service_feed
    categories:
      - 'Emergency Warning'
      - 'Watch and Act'
      - 'Advice'


# ================
# Device
# ================

sensor: !include sensors.yaml
media_player: !include media_player.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include cameras.yaml
climate: !include climate.yaml
light: !include light.yaml

# # https://www.home-assistant.io/integrations/android_ip_webcam/
# # ...turns any Android phone or tablet into a network camera with multiple viewing options
# android_ip_webcam:
#   - name: Stove
#     host: 192.168.86.246
#     port: 8080
#     # username: james
#     # password: !secret basic

switch:
  - platform: broadlink
    mac: "C8:F7:42:16:BC:E8"
    # switches: !include broadlink.yaml

# # Replaced by sonoff
# tuya:
#   username: !secret tuya_username
#   password: !secret tuya_password
#   country_code: 61
#   platform: smart_life

# Cf. https://github.com/peterbuga/HASS-sonoff-ewelink
# Cf. https://github.com/AlexxIT/SonoffLAN
# Pow R2 and two switches
sonoff:
  username: !secret ewelink_username
  password: !secret public
  force_update: [temperature, power]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]


# ================
# Services
# ================

sun:

weather:
  - platform: bom
    station: IDN60901.94759
    name: Terrey Hills

tts:
  - platform: google_translate

influxdb:
  host: sniper.lan
  port: 8086
  database: ha
  username: !secret influxdb_user
  password: !secret master3
  max_retries: 3
  default_measurement: state

google:
  client_id: !secret google_hassio_client_id
  client_secret: !secret google_hassio_secret
  track_new_calendar: true

# glances:

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_secret

# Cf. https://www.home-assistant.io/integrations/airvisual/
airvisual:
  api_key: !secret airvisual-key
  #monitored_conditions:
  #  - us
  #city: hornsby
  #state: new-south-wales
  #country: australia

# zoneminder:
#   host: localhost:8443
#   ssl: true


# ================
# Inputs
# ================

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
  frontdoor_unlock:
    name: Frontdoor unlocked
    initial: off
    icon: mdi:lock-outline
  house_alarmed:
    name: House alarmed
    initial: off
    icon: mdi:shield-home
  smsl_power:
    name: SMSL AD18 power
    initial: off
    icon: mdi:power
  smsl_mute:
    name: SMSL AD18 smsl_mute
    initial: off
    icon: mdi:volume-mute

input_number:
  smsl_volume:
    name: SMSL volume
    initial: 0
    min: 0
    max: 30
    step: 2

input_select:
  frontdoor_mode:
    name: Mode of frontdoor
    options:
      - Locked
      - Unlocked
      - Passive
    initial: Locked
    icon: mdi:lock-outline
  smsl_source:
    name: Input source for SMSL AD18
    options:
      - USB
      - Optical 1
      - Optical 2
      - Coaxial
      - Bluetooth
      - Auxillary
    icon: mdi:audio-video
    initial: USB

timer:
  zigbee_permit_join:
    name: Zibbee permit join remaining
    duration: 600
  arrived_home:
    name: Frontdoor unlock remaining
    duration: 180


# ================
# Extensions
# ================

# Cf. https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger
webhook:

shell_command:
  motion_on: 'curl http://sniper.lan:7999/1/detection/start'
  motion_off: 'curl http://sniper.lan:7999/1/detection/pause'

# zigbee2mqtt_networkmap:
#   #topic: zigbee2mqtt

panel_iframe: !include panel_iframe.yaml
