# ================
# Core
# ================

homeassistant:
  customize: !include customize.yaml

default_config:

http:
  base_url: https://famidamily.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:
  themes: !include_dir_merge_named themes

hacs:
  token: !secret my_github_hacs_token
  sidepanel_title: Community Store

# Different ways of splitting code at
# https://www.home-assistant.io/docs/configuration/splitting_configuration/#advanced-usage
automation: !include_dir_merge_list automations
group: !include groups.yaml
logbook: !include logbook.yaml
history: !include history.yaml
notify: !include notifications.yaml
recorder: !include recorder.yaml
#alert: !include alerts.yaml
#script: !include scripts.yaml

# ================
# Geolocation
# ================

person: !include person.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml

#owntracks:

geo_location:
  - platform: nsw_rural_fire_service_feed
    categories:
      - 'Emergency Warning'
      - 'Watch and Act'
      - 'Advice'

# ================
# Device
# ================

sensor: !include sensors.yaml
media_player: !include media_player.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include cameras.yaml
climate: !include climate.yaml
light: !include light.yaml

# # https://www.home-assistant.io/integrations/android_ip_webcam/
# # ...turns any Android phone or tablet into a network camera with multiple viewing options
# android_ip_webcam:
#   - name: Stove
#     host: 192.168.86.246
#     port: 8080
#     # username: james
#     # password: !secret basic

switch:
  - platform: broadlink
    host: 192.168.86.198
    mac: "C8:F7:42:16:BC:E8"
    type: rm_mini
    switches: !include broadlink.yaml

# # Replaced by sonoff
# tuya:
#   username: !secret tuya_username
#   password: !secret tuya_password
#   country_code: 61
#   platform: smart_life

# Cf. https://github.com/peterbuga/HASS-sonoff-ewelink
# Pow R2 and two switches
sonoff:
  username: !secret ewelink_username
  password: !secret public
  api_region: us
  #entity_prefix: True

# ================
# Services
# ================

sun:

weather:
  - platform: bom
    station: IDN60901.94759
    name: Terrey Hills

# # Cf. https://www.home-assistant.io/integrations/wwlln/
# wwlln:
#   radius: 25
#   latitude: -33.7008
#   longitude: 151.086

# Integrate MQTT into homeassistant
mqtt:
  #broker: core-mosquitto
  broker: famidamily.duckdns.org  # Remove if you want to use builtin-in MQTT broker
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  # discovery_prefix: zigbee2mqtt
  username: !secret mqtt_user
  password: !secret master3

tts:
  - platform: google_translate

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret basic
  max_retries: 3
  default_measurement: state

google:
  client_id: !secret google_hassio_client_id
  client_secret: !secret google_hassio_secret
  track_new_calendar: true

# Cf. https://www.home-assistant.io/integrations/pi_hole
pi_hole:
  host: localhost:4865

glances:

# ================
# Inputs
# ================

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
  frontdoor_unlock:
    name: Frontdoor unlocked
    initial: off
    icon: mdi:lock-outline
  house_alarmed:
    name: House alarmed
    initial: off
    icon: mdi:shield-home

input_select:
  frontdoor_mode:
    name: Mode of frontdoor
    options:
      - Locked
      - Unlocked
      - Passive
    initial: Locked
    icon: mdi:lock-outline

timer:
  zigbee_permit_join:
    name: Zibbee permit join remaining
    duration: 600
  arrived_home:
    name: Frontdoor unlock remaining
    duration: 180

# ================
# Extensions
# ================

webhook:

shell_command:
  motion_on: 'curl http://famidamily.duckdns.org:7999/1/detection/start'
  motion_off: 'curl http://famidamily.duckdns.org:7999/1/detection/pause'

zigbee2mqtt_networkmap:
  #topic: zigbee2mqtt

panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    icon: 'mdi:graphql'
    # You can set the graphviz engine via URL Parameter: 
    # map.html?engine=circo (Default: circo,
    # [Supported Engines](https://github.com/mdaines/viz.js/wiki/Supported-Graphviz-Features))  
    url: '/local/zigbee2mqtt_networkmap/map.html'
