# ================
# Core
# ================

homeassistant:
  customize: !include customize.yaml

default_config:

http:
  base_url: https://famidamily.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:
  themes: !include_dir_merge_named themes

hacs:
  token: !secret my_github_hacs_token
  sidepanel_title: Community Store

# Different ways of splitting code at
# https://www.home-assistant.io/docs/configuration/splitting_configuration/#advanced-usage
automation: !include_dir_merge_list automations
group: !include groups.yaml
logbook: !include logbook.yaml
notify: !include notifications.yaml
recorder: !include recorder.yaml
#alert: !include alerts.yaml
#script: !include scripts.yaml

# ================
# Geolocation
# ================

person: !include person.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml

#owntracks:

geo_location:
  - platform: nsw_rural_fire_service_feed
    categories:
      - 'Emergency Warning'
      - 'Watch and Act'
      - 'Advice'

# ================
# Device
# ================

sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include cameras.yaml
climate: !include climate.yaml
light: !include light.yaml

# https://www.home-assistant.io/integrations/android_ip_webcam/
# ...turns any Android phone or tablet into a network camera with multiple viewing options
android_ip_webcam:
  - name: Stove
    host: 192.168.86.246
    port: 8080
    # username: james
    # password: !secret basic

switch:
  - platform: broadlink
    host: 192.168.86.198
    mac: "C8:F7:42:16:BC:E8"
    type: rm_mini
    switches: !include broadlink.yaml

# State is always on and unable to control (but port 8001 is open)
# Samsung UA65HU9000 UHD LED TV 2014 (WiFi)
#
# $ nmap -A -T4 192.168.86.72
# PORT     STATE    SERVICE        VERSION
# 4443/tcp open     ssl/pharos?
# |_ssl-date: 1970-01-01T07:46:33+00:00; -49y317d01h46m14s from scanner time.
# 5101/tcp open     tcpwrapped
# 6000/tcp filtered X11
# 7676/tcp open     upnp           AllShare UPnP
# 8000/tcp open     http-alt
# | fingerprint-strings: 
# |   FourOhFourRequest, HTTPOptions: 
# |     HTTP/1.1 500 Internal Server Error
# |     Content-Type: text/plain
# |     Date: Thu, 01 Jan 1970 07:46:22 GMT
# |     Connection: close
# |   GetRequest: 
# |     HTTP/1.1 500 Internal Server Error
# |     Content-Type: text/plain
# |     Date: Thu, 01 Jan 1970 07:46:21 GMT
# |_    Connection: close
# |_http-cors: GET POST PUT DELETE OPTIONS
# |_http-open-proxy: Proxy might be redirecting requests
# |_http-title: Site doesn't have a title.
#
# 8001/tcp open     http           Node.js Express framework
# |_http-cors: GET POST PUT DELETE
# |_http-title: 404 : Not Found
# Cf. https://github.com/twbs/bootstrap
#
# 8080/tcp open     http           lighttpd
# |_http-title: 404 - Not Found
# 8443/tcp open     ssl/https-alt?
# |_ssl-date: 1970-01-01T07:46:28+00:00; -49y317d01h46m15s from scanner time.

media_player:
  - platform: samsungtv
    name: Samsung TV
    host: 192.168.86.72
    port: 8001
    mac: 54:88:0e:23:6d:b3

# # New platform from the community store
# media_player:
#   - platform: samsungtv_custom
#     name: Samsung TV
#     mac: 54:88:0e:23:6d:b3
#     host: 192.168.86.72
#     port: 8001
#     sourcelist: '{"Chromecast": "KEY_HDMI4"}'
#     protocol: ctl  # ctl, ws, ctl_beta, ctl_qled

# ================
# Services
# ================

sun:

weather:
  - platform: bom
    station: IDN60901.94759
    name: Terrey Hills

# Cf. https://www.home-assistant.io/integrations/wwlln/
wwlln:
  radius: 25
  latitude: -33.7008
  longitude: 151.086

# Integrate MQTT into homeassistant
mqtt:
  #broker: core-mosquitto
  broker: 192.168.86.168  # Remove if you want to use builtin-in MQTT broker
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  # discovery_prefix: zigbee2mqtt
  username: !secret mqtt_user
  password: !secret master3

tts:
  - platform: google_translate

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret basic
  max_retries: 3
  default_measurement: state

google:
  client_id: !secret google_hassio_client_id
  client_secret: !secret google_hassio_secret
  track_new_calendar: true

pi_hole:
  host: localhost:4865
  ssl: true
  verify_ssl: false

# ================
# Inputs
# ================

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
  frontdoor_unlock:
    name: Frontdoor unlocked
    initial: off
    icon: mdi:lock-outline
  house_alarmed:
    name: House alarmed
    initial: off
    icon: mdi:shield-home

input_select:
  frontdoor_mode:
    name: Mode of frontdoor
    options:
      - Locked
      - Unlocked
      - Passive
    initial: Locked
    icon: mdi:lock-outline

timer:
  zigbee_permit_join:
    name: Zibbee permit join remaining
    duration: 600
  arrived_home:
    name: Frontdoor unlock remaining
    duration: 180

# ================
# Extensions
# ================

webhook:

shell_command:
  motion_on: 'curl http://famidamily.duckdns.org:7999/1/detection/start'
  motion_off: 'curl http://famidamily.duckdns.org:7999/1/detection/pause'

zigbee2mqtt_networkmap:
  #topic: zigbee2mqtt

panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    icon: 'mdi:graphql'
    # You can set the graphviz engine via URL Parameter: 
    # map.html?engine=circo (Default: circo,
    # [Supported Engines](https://github.com/mdaines/viz.js/wiki/Supported-Graphviz-Features))  
    url: '/local/zigbee2mqtt_networkmap/map.html'
