# ================
# Core
# ================

homeassistant:
  customize: !include customize.yaml

default_config:

http:
  base_url: https://famidamily.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:
  themes: !include themes/dark_cyan.yaml

hacs:
  token: !secret my_github_hacs_token
  sidepanel_title: Community Store

# Different ways of splitting code at
# https://www.home-assistant.io/docs/configuration/splitting_configuration/#advanced-usage
automation: !include_dir_merge_list automations
group: !include groups.yaml
logbook: !include logbook.yaml
notify: !include notifications.yaml
recorder: !include recorder.yaml
#alert: !include alerts.yaml
#script: !include scripts.yaml


# ================
# Geolocation
# ================

zone: !include zones.yaml

owntracks:

geo_location:
  - platform: nsw_rural_fire_service_feed
    categories:
      - 'Emergency Warning'
      - 'Watch and Act'
      - 'Advice'

device_tracker: !include device_tracker.yaml


# ================
# Device
# ================

sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include cameras.yaml
climate: !include climate.yaml
light: !include light.yaml

switch:
  - platform: broadlink
    host: 192.168.86.198
    mac: "C8:F7:42:16:BC:E8"
    type: rm_mini
    switches: !include broadlink.yaml

# State is always on and unable to control (but port 8001 is open)
# Samsung UA65HU9000 UHD LED TV 2014 (WiFi)
media_player:
  - platform: samsungtv
    name: Samsung TV
    host: 192.168.86.72
    port: 8001
    mac: 54:88:0e:23:6d:b3


# ================
# Services
# ================

sun:

weather:
  - platform: bom
    station: IDN60901.94759
    name: Terrey Hills

mqtt:
  broker: famidamily.duckdns.org
  discovery: true

tts:
  - platform: google_translate

influxdb: !include influxdb.yaml

google:
  client_id: !secret google_hassio_client_id
  client_secret: !secret google_hassio_secret
  track_new_calendar: true

pi_hole:
  host: localhost:4865
  ssl: true
  verify_ssl: false


# ================
# Inputs
# ================

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 300


# ================
# Extensions
# ================

webhook:

zigbee2mqtt_networkmap:
  #topic: zigbee2mqtt

panel_iframe:
  networkmap:
    title: 'Zigbee Map'
    icon: 'mdi:graphql'
    # You can set the graphviz engine via URL Parameter: 
    # map.html?engine=circo (Default: circo,
    # [Supported Engines](https://github.com/mdaines/viz.js/wiki/Supported-Graphviz-Features))  
    url: '/local/zigbee2mqtt_networkmap/map.html'
