# State is always on and unable to control (but port 8001 is open)
# Samsung UA65HU9000 UHD LED TV 2014 (WiFi)
#
# $ nmap -A -T4 192.168.86.72
# PORT     STATE    SERVICE        VERSION
# 4443/tcp open     ssl/pharos?
# |_ssl-date: 1970-01-01T07:46:33+00:00; -49y317d01h46m14s from scanner time.
# 5101/tcp open     tcpwrapped
# 6000/tcp filtered X11
# 7676/tcp open     upnp           AllShare UPnP
# 8000/tcp open     http-alt
# | fingerprint-strings: 
# |   FourOhFourRequest, HTTPOptions: 
# |     HTTP/1.1 500 Internal Server Error
# |     Content-Type: text/plain
# |     Date: Thu, 01 Jan 1970 07:46:22 GMT
# |     Connection: close
# |   GetRequest: 
# |     HTTP/1.1 500 Internal Server Error
# |     Content-Type: text/plain
# |     Date: Thu, 01 Jan 1970 07:46:21 GMT
# |_    Connection: close
# |_http-cors: GET POST PUT DELETE OPTIONS
# |_http-open-proxy: Proxy might be redirecting requests
# |_http-title: Site doesn't have a title.
#
# 8001/tcp open     http           Node.js Express framework
# |_http-cors: GET POST PUT DELETE
# |_http-title: 404 : Not Found
# Cf. https://github.com/twbs/bootstrap
#
# 8080/tcp open     http           lighttpd
# |_http-title: 404 - Not Found
# 8443/tcp open     ssl/https-alt?
# |_ssl-date: 1970-01-01T07:46:28+00:00; -49y317d01h46m15s from scanner time.

  # - platform: samsungtv
  #   name: Samsung TV
  #   host: 192.168.86.72
  #   port: 8001
  #   mac: 54:88:0e:23:6d:b3

# # New platform from the community store
#   - platform: samsungtv_custom
#     name: Samsung TV
#     mac: 54:88:0e:23:6d:b3
#     host: 192.168.86.72
#     port: 8001
#     sourcelist: '{"Chromecast": "KEY_HDMI4"}'
#     protocol: ctl  # ctl, ws, ctl_beta, ctl_qled


- platform: universal
  name: SMSL AD18 Hi-Fi
  # children:
  #   - media_player.harman_kardon_avr
  commands:
    turn_on:
      service: remote.send_command
      data:
        entity_id: remote.irblaster_remote
        device: smsl
        command: Power
    turn_off:
      service: remote.send_command
      data:
        entity_id: remote.irblaster_remote
        device: smsl
        command: Power
    volume_up:
      service: remote.send_command
      data:
        entity_id: remote.irblaster_remote
        device: smsl
        command: Volume up
    volume_down:
      service: remote.send_command
      data:
        entity_id: remote.irblaster_remote
        device: smsl
        command: Volume down
    volume_mute:
      service: remote.send_command
      data:
        entity_id: remote.irblaster_remote
        device: smsl
        command: Mute
  attributes:
    state: input_boolean.smsl_power|state
    is_volume_muted: input_boolean.smsl_mute|state
    volume_level: input_number.smsl_volume|state
    source: input_select.smsl_source|state
    source_list: input_select.smsl_source|options

