- platform: google_wifi

- platform: github
  access_token: !secret my_github_repo_token
  repositories:
    - path: 'jamesawebb/homeassistant'
    
# https://www.home-assistant.io/components/systemmonitor/
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: swap_use_percent
  - type: last_boot
  - type: load_5m

- platform: alpha_vantage
  api_key: !secret alpha_vantage_key
  symbols:
    - symbol: GOOG
      name: Google Class C
    # - symbol: GOOGL
    #   name: Google Class A
  foreign_exchange:
    - name: usd2aud
      from: USD
      to: AUD

- platform: template
  sensors:
    google_aud:
      friendly_name: "Google stock adjusted to AUD"
      unit_of_measurement: "$AUD"
      value_template: "{{ (float((states.sensor.google_class_c.state)) * float((states.sensor.usd2aud.state))) | round(2)}}"
    solar_angle:
      friendly_name: "Sun Angle"
      unit_of_measurement: '°'
      value_template: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"
    sunrise:
      value_template: "{{ state_attr('sun.sun', 'next_rising') }}"

- platform: pi_hole
  host: localhost:4865
  monitored_conditions:
    - ads_blocked_today
    - dns_queries_today
    - unique_clients

# - platform: rpi_power
#   text_state: false

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless

# Frontdoor sensor
- platform: "mqtt"
  state_topic: "zigbee2mqtt/frontdoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  state_topic: "zigbee2mqtt/frontdoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"

# Laundry/Kitching sliding door sensor
- platform: "mqtt"
  state_topic: "zigbee2mqtt/laundry_sliding_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  state_topic: "zigbee2mqtt/laundry_sliding_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"

# Patio sliding door
- platform: "mqtt"
  state_topic: "zigbee2mqtt/patio_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  state_topic: "zigbee2mqtt/patio_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"

- platform: yr     # Weather prediction

# https://www.home-assistant.io/components/bom/
- platform: bom
  station: !secret my_bom_station
  name: !secret my_bom_name
  monitored_conditions:
    - apparent_t
    - delta_t
    - gust_kmh
    - gust_kt
    - air_temp
    - dewpt
    - rain_trace
    - rel_hum
    - wind_dir
    - wind_spd_kmh
    - wind_spd_kt

# https://home-assistant.io/components/sensor.bom_forecast/
# https://github.com/DavidFW1960/bom_forecast
- platform: bom_forecast
  product_id: !secret my_bom_product_id2
  name: !secret my_bom_name
  forecast_days: 6
  rest_of_today: true
  friendly: false
  friendly_state_format: '{max}, {summary}'
  monitored_conditions:
    - 'max'
    - 'min'
    - 'chance_of_rain'
    - 'possible_rainfall'
    - 'summary'
    - 'detailed_summary'
    - 'icon'

# https://www.home-assistant.io/components/mold_indicator/
- platform: mold_indicator
  indoor_temp_sensor: sensor.bedroom_temperature
  indoor_humidity_sensor: sensor.bedroom_relative_humidity
  outdoor_temp_sensor: sensor.outside_patio_temperature
  calibration_factor: 2.0

- platform: template
  sensors:
    bom_current_text:
      value_template: >
          {% set val = states('sensor.bom_terrey_hills_summary_0').split('.')[0] %} 
          {{ val | title }}
    bom_forecast_0:
      entity_id:
        - sensor.bom_today_max
        - sensor.bom_today_min
        - sensor.bom_terrey_hills_chance_of_rain_0
        - sensor.bom_terrey_hills_icon_0
      friendly_name: "Today"
      value_template: >
        {{states('sensor.bom_today_max')|round(0)}}°/{{states('sensor.bom_today_min')|round(0)}}°/{{states('sensor.bom_terrey_hills_chance_of_rain_0')|round(0)}}%
      entity_picture_template: >-
        {%- if states('sun.sun') == 'below_horizon' and (states('sensor.bom_terrey_hills_icon_0') == 'fog' or states('sensor.bom_terrey_hills_icon_0') == 'haze' or states('sensor.bom_terrey_hills_icon_0') == 'light-showers' or states('sensor.bom_terrey_hills_icon_0') == 'partly-cloudy' or states('sensor.bom_terrey_hills_icon_0') == 'showers') -%}
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_terrey_hills_icon_0') ~ '-night.png' }}
        {%- else -%}
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_terrey_hills_icon_0') ~ '.png' }}
        {%- endif -%}
    bom_forecast_1:
      entity_id:
        - sensor.bom_terrey_hills_max_temp_c_1
        - sensor.bom_terrey_hills_min_temp_c_1
        - sensor.bom_terrey_hills_chance_of_rain_1
        - sensor.bom_terrey_hills_icon_1
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
        {{ date | timestamp_custom('Tomorrow (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_terrey_hills_max_temp_c_1')|round(0)}}°/{{states('sensor.bom_terrey_hills_min_temp_c_1')|round(0)}}°/{{states('sensor.bom_terrey_hills_chance_of_rain_1')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_terrey_hills_icon_1') ~ '.png' }}
    bom_forecast_2:
      entity_id:
        - sensor.bom_terrey_hills_max_temp_c_2
        - sensor.bom_terrey_hills_min_temp_c_2
        - sensor.bom_terrey_hills_chance_of_rain_2
        - sensor.bom_terrey_hills_icon_2
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_terrey_hills_max_temp_c_2')|round(0)}}°/{{states('sensor.bom_terrey_hills_min_temp_c_2')|round(0)}}°/{{states('sensor.bom_terrey_hills_chance_of_rain_2')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_terrey_hills_icon_2') ~ '.png' }}
    bom_forecast_3:
      entity_id:
        - sensor.bom_terrey_hills_max_temp_c_3
        - sensor.bom_terrey_hills_min_temp_c_3
        - sensor.bom_terrey_hills_chance_of_rain_3
        - sensor.bom_terrey_hills_icon_3
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_terrey_hills_max_temp_c_3')|round(0)}}°/{{states('sensor.bom_terrey_hills_min_temp_c_3')|round(0)}}°/{{states('sensor.bom_terrey_hills_chance_of_rain_3')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_terrey_hills_icon_3') ~ '.png' }}
    bom_forecast_4:
      entity_id:
        - sensor.bom_terrey_hills_max_temp_c_4
        - sensor.bom_terrey_hills_min_temp_c_4
        - sensor.bom_terrey_hills_chance_of_rain_4
        - sensor.bom_terrey_hills_icon_4
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_terrey_hills_max_temp_c_4')|round(0)}}°/{{states('sensor.bom_terrey_hills_min_temp_c_4')|round(0)}}°/{{states('sensor.bom_terrey_hills_chance_of_rain_4')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_terrey_hills_icon_4') ~ '.png' }}
    bom_forecast_5:
      entity_id:
        - sensor.bom_terrey_hills_max_temp_c_5
        - sensor.bom_terrey_hills_min_temp_c_5
        - sensor.bom_terrey_hills_chance_of_rain_5
        - sensor.bom_terrey_hills_icon_5
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_terrey_hills_max_temp_c_5')|round(0)}}°/{{states('sensor.bom_terrey_hills_min_temp_c_5')|round(0)}}°/{{states('sensor.bom_terrey_hills_chance_of_rain_5')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_terrey_hills_icon_5') ~ '.png' }}
    bom_forecast_6:
      entity_id:
        - sensor.bom_terrey_hills_max_temp_c_6
        - sensor.bom_terrey_hills_min_temp_c_6
        - sensor.bom_terrey_hills_chance_of_rain_6
        - sensor.bom_terrey_hills_icon_6
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_terrey_hills_max_temp_c_6')|round(0)}}°/{{states('sensor.bom_terrey_hills_min_temp_c_6')|round(0)}}°/{{states('sensor.bom_terrey_hills_chance_of_rain_6')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_terrey_hills_icon_6') ~ '.png' }}
    bom_today_max:
      entity_id:
        - sensor.bom_terrey_hills_max_temp_c_0
        - sensor.today_temp_bom_mean
      value_template: >
        {%- if states('sensor.bom_terrey_hills_max_temp_c_0') == 'n/a' -%} 
          {{ state_attr('sensor.today_temp_bom_mean', 'max_value') }}
        {% else %}
          {{ states('sensor.bom_terrey_hills_max_temp_c_0') }}
        {% endif %}
    bom_today_min:
      entity_id:
        - sensor.bom_terrey_hills_min_temp_c_0
        - sensor.today_temp_bom_mean
      value_template: >
        {%- if states('sensor.bom_terrey_hills_min_temp_c_0') == 'n/a' -%} 
          {{ state_attr('sensor.today_temp_bom_mean', 'min_value') }}
        {% else %}
          {{ states('sensor.bom_terrey_hills_min_temp_c_0') }}
        {% endif %}

- platform: statistics
  name: today_temp_bom
  sampling_size: 150
  entity_id: sensor.bom_terrey_hills_air_temp_c
  max_age:
    hours: 24
