# Looks like Google have removed the API for this platform.
#- platform: google_wifi

# Cf. https://www.home-assistant.io/components/systemmonitor/
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: swap_use_percent
  - type: last_boot
  - type: load_5m

# Removed in lieu of Glances integration
# # Cf. https://github.com/hassio-addons/addon-glances/blob/v0.5.5/README.md
# - platform: glances
#   host: 127.0.0.1
#   port: 61209
#   version: 3
#   resources:
#     - 'processor_load'
#     - 'memory_use_percent'
#     - 'disk_use_percent'

- platform: github
  access_token: !secret my_github_repo_token
  repositories:
    - path: 'jamesawebb/homeassistant'
    
- platform: alpha_vantage
  api_key: !secret alpha_vantage_key
  symbols:
    - symbol: GOOG
      name: Google Class C
    # - symbol: GOOGL
    #   name: Google Class A
  foreign_exchange:
    - name: usd2aud
      from: USD
      to: AUD

- platform: template
  sensors:
    google_aud:
      friendly_name: "Google stock adjusted to AUD"
      unit_of_measurement: "$AUD"
      value_template: "{{ (float(states('sensor.google_class_c')) * float(states('sensor.usd2aud'))) | round(2)}}"
    solar_angle:
      friendly_name: "Sun Angle"
      unit_of_measurement: '°'
      value_template: "{{ '%+.1f'|format(state_attr('sun.sun', 'elevation')) }}"
    sunrise:
      value_template: "{{ state_attr('sun.sun', 'next_rising') }}"

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless

- platform: mqtt
  name: Zigbee2mqtt Networkmap
  # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
  state_topic: zigbee2mqtt/bridge/networkmap/raw
  value_template: >-
    {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
  # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
  json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

# Front door sensor
- platform: "mqtt"
  state_topic: "zigbee2mqtt/front_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  state_topic: "zigbee2mqtt/front_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"

# Pantry sliding door sensor
- platform: "mqtt"
  state_topic: "zigbee2mqtt/pantry_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  state_topic: "zigbee2mqtt/pantry_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"

# Patio sliding door
- platform: "mqtt"
  state_topic: "zigbee2mqtt/patio_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  state_topic: "zigbee2mqtt/patio_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"

# Grarage entry
- platform: "mqtt"
  state_topic: "zigbee2mqtt/garage_entry"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  state_topic: "zigbee2mqtt/garage_entry"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.linkquality }}"

# - platform: yr     # Weather prediction

# # Cf. https://www.home-assistant.io/components/bom/
# - platform: bom
#   station: !secret my_bom_station
#   name: !secret my_bom_name
#   monitored_conditions:
#     - apparent_t
#     - delta_t
#     - gust_kmh
#     - gust_kt
#     - air_temp
#     - dewpt
#     - rain_trace
#     - rel_hum
#     - wind_dir
#     - wind_spd_kmh
#     - wind_spd_kt

# # Cf. https://home-assistant.io/components/sensor.bom_forecast/
# # Cf. https://github.com/DavidFW1960/bom_forecast
# - platform: bom_forecast
#   product_id: !secret my_bom_product_id2
#   name: !secret my_bom_name
#   forecast_days: 6
#   rest_of_today: true
#   friendly: false
#   friendly_state_format: '{max}, {summary}'
#   monitored_conditions:
#     - 'chance_of_rain'
#     - 'detailed_summary'
#     - 'icon'
#     - 'max'
#     - 'min'
#     - 'possible_rainfall'
#     - 'summary'
#     - 'fire_danger'
#     - 'uv_alert'

# Cf. https://www.home-assistant.io/components/mold_indicator/
- platform: mold_indicator
  indoor_temp_sensor: sensor.bedroom_temperature
  indoor_humidity_sensor: sensor.bedroom_relative_humidity
  outdoor_temp_sensor: sensor.outside_patio_temperature
  calibration_factor: 2.0

- platform: template
  sensors:
    bedroom_diff:
      value_template: "{{ (states('sensor.outside_patio_temperature') | float - states('sensor.bedroom_temperature') | float) | round }}"
    lounge_diff:
      value_template: "{{ (states('sensor.outside_patio_temperature') | float - states('sensor.lounge_temperature') | float) | round }}"
    garage_internal_diff:
      value_template: "{{ (states('sensor.garage_temperature') | float - states('sensor.lounge_temperature') | float) | round }}"
    garage_external_diff:
      value_template: "{{ (states('sensor.outside_patio_temperature') | float - states('sensor.garage_temperature') | float) | round }}"
    mould_degrees:
      friendly_name: "Mould Indicator"
      unit_of_measurement: °C
      value_template: "{{ states('sensor.mold_indicator') }}"
    bom_today_max:
      value_template: >
        {{ state_attr('sensor.today_temp_bom', 'max_value') }}
    bom_today_min:
      value_template: >
        {{ state_attr('sensor.today_temp_bom', 'min_value') }}
    bom_current_text:
      value_template: >
          {% set val = states('sensor.hornsby_short_text_0').split('.')[0] %} 
          {{ val | title }}
    bom_forecast_0:
      friendly_name: "Today"
      value_template: >
        {% if states('sensor.hornsby_temp_min_0') == 'unknown' %} {% set min = states('sensor.bom_today_min') %} {% else %} {% set min = states('sensor.hornsby_temp_min_0') %} {% endif %}
        {% if states('sensor.hornsby_temp_max_0') == 'unknown' %} {% set max = states('sensor.bom_today_max') %} {% else %} {% set max = states('sensor.hornsby_temp_max_0') %} {% endif %}
        {{ max|round(0)}}°/{{ min|round(0)}}°/{{states('sensor.hornsby_rain_chance_0')|round(0)}}%
      entity_picture_template: >-
        {%- if states('sun.sun') == 'below_horizon' and (states('sensor.hornsby_icon_descriptor_0') == 'fog' or states('sensor.hornsby_icon_descriptor_0') == 'haze' or states('sensor.hornsby_icon_descriptor_0') == 'light-showers' or states('sensor.hornsby_icon_descriptor_0') == 'partly-cloudy' or states('sensor.hornsby_icon_descriptor_0') == 'showers' or states('sensor.hornsby_icon_descriptor_0') == 'shower' or states('sensor.hornsby_icon_descriptor_0') == 'light_showers' or states('sensor.hornsby_icon_descriptor_0') == 'partly_cloudy') -%}
        {{ '/local/icons/bom_icons/' ~ states('sensor.hornsby_icon_descriptor_0') ~ '-night.png' }}
        {%- else -%}
        {{ '/local/icons/bom_icons/' ~ states('sensor.hornsby_icon_descriptor_0') ~ '.png' }}
        {%- endif -%}
    bom_forecast_1:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
        {{ date | timestamp_custom('Tomorrow (%-d/%-m)') }}
      value_template: >
        {{states('sensor.hornsby_temp_max_1')|round(0)}}°/{{states('sensor.hornsby_temp_min_1')|round(0)}}°/{{states('sensor.hornsby_rain_chance_1')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.hornsby_icon_descriptor_1') ~ '.png' }}
    bom_forecast_2:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.hornsby_temp_max_2')|round(0)}}°/{{states('sensor.hornsby_temp_min_2')|round(0)}}°/{{states('sensor.hornsby_rain_chance_2')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.hornsby_icon_descriptor_2') ~ '.png' }}
    bom_forecast_3:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.hornsby_temp_max_3')|round(0)}}°/{{states('sensor.hornsby_temp_min_3')|round(0)}}°/{{states('sensor.hornsby_rain_chance_3')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.hornsby_icon_descriptor_3') ~ '.png' }}
    bom_forecast_4:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.hornsby_temp_max_4')|round(0)}}°/{{states('sensor.hornsby_temp_min_4')|round(0)}}°/{{states('sensor.hornsby_rain_chance_4')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.hornsby_icon_descriptor_4') ~ '.png' }}
    bom_forecast_5:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.hornsby_temp_max_5')|round(0)}}°/{{states('sensor.hornsby_temp_min_5')|round(0)}}°/{{states('sensor.hornsby_rain_chance_5')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.hornsby_icon_descriptor_5') ~ '.png' }}
    bom_forecast_6:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.hornsby_temp_max_6')|round(0)}}°/{{states('sensor.hornsby_temp_min_6')|round(0)}}°/{{states('sensor.hornsby_rain_chance_6')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.hornsby_icon_descriptor_6') ~ '.png' }}
    bom_uv_alert:
      value_template: >
          UV Today: Sun Protection 
          {{ as_timestamp(states('sensor.hornsby_uv_start_time_0')) | timestamp_custom(' %I:%M%p') | lower | replace(" 0", "") }} to {{ as_timestamp(states('sensor.hornsby_uv_end_time_0')) | timestamp_custom(' %I:%M%p') | lower | replace(" 0", "") }}, UV Index predicted to reach {{ states('sensor.hornsby_uv_max_index_0') }} [{{ states('sensor.hornsby_uv_category_0') }}]
    bom_fire_danger:
      value_template: "Fire Danger Today: {{ states('sensor.hornsby_fire_danger_0') }}"

# - platform: statistics
#   name: today_temp_bom
#   sampling_size: 150
#   entity_id: sensor.bom_terrey_hills_air_temp_c
#   max_age:
#     hours: 24

# - platform: average
#   name: today_temp_bom
#   entities:
#     - sensor.terrey_hills_temp
#   start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#   end: '{{ now() }}'

# - platform: apcupsd
#   resources:
#     - apc
#     - date
#     - hostname
#     - version
#     - upsname
#     - cable
#     - driver
#     - upsmode
#     - starttime
#     - model
#     - status
#     - linev
#     - loadpct
#     - bcharge
#     - timeleft
#     - mbattchg
#     - mintimel
#     - maxtime
#     # - maxlinev
#     # - minlinev
#     - outputv

# Cf. https://www.waternsw.com.au/water-quality/catchment/sub-catchment/warragamba
- platform: waternsw
  name: Warragamba Dam
  site_id: 212243
  from_variable: 130.00
  to_variable: 136.00
  unit_of_measure: ML

# Cf. https://www.waternsw.com.au/water-quality/catchment/sub-catchment/nepean
- platform: waternsw
  name: Nepean Dam
  site_id: 212205
  from_variable: 132.00
  to_variable: 132.00
  unit_of_measure: ML

- platform: season
