- alias: 'Update BOM Icons'
  trigger:
    - event: start
      platform: homeassistant
    - platform: time
      at: '03:01:00'
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.bom_forecast_0
