esphome:
  name: doorbell
  platform: esp32
  board: mhetesp32minikit

wifi:
  ssid: !secret network
  password: !secret wpa2

logger:

api:
  password: !secret basic

ota:
  password: !secret basic

switch:
  - platform: gpio
    pin:
      number: 22
      mode: OUTPUT
    id: doorstrike
    name: doorstrike_relay

  - platform: gpio
    pin:
      number: 18
      mode: OUTPUT
    id: flicker
    name: button_illumination_relay

  - platform: template
    name: "Door Strike Release Override"
    icon: "mdi:door"
    turn_on_action:
      - switch.turn_on: doorstrike
      - delay: 7s
      - switch.turn_off: doorstrike

  - platform: template
    name: "Button Flicker"
    icon: "mdi:flash"
    turn_on_action:
      - switch.toggle: flicker
      - delay: 333ms
      - switch.toggle: flicker
      - delay: 333ms

# Scan for BLE devices
esp32_ble_tracker:
  # This option has been removed in 1.14 (Reason: it never had an effect).
  #scan_interval: 60s

binary_sensor:
  - platform: gpio
    id: dingdong
    name: "Doorbell Press"
    pin:
      number: 23
      mode: INPUT_PULLDOWN
    # filters:
    # - delayed_on: 100ms
    # - lambda: |-
    #     if (id(other_binary_sensor).state) {
    #       return x;
    #     } else {
    #       return {};
    #     }
    # on_press:
    #   then:
    #     - switch.turn_on: doorstrike
    #     - delay: 7s
    #     - switch.turn_off: doorstrike

# sensor: signal strength
# binary_sensor: presence detection

# No point scanning the MAC address - it's not used
# Cf. https://stackoverflow.com/questions/28602672/android-5-static-bluetooth-mac-address-for-ble-advertising

  # - platform: ble_presence
  #   mac_address: !secret bt_james_mobile
  #   name: "James Pixel 2XL"

  # - platform: ble_presence
  #   mac_address: !secret bt_chianti_mobile
  #   name: "Chianti Pixel 2XL"

# sensor:
#   - platform: ble_rssi
#     mac_address: !secret bt_james_mobile
#     name: "James Pixel 2XL RSSI"

#   - platform: ble_rssi
#     mac_address: !secret bt_chianti_mobile
#     name: "Chianti Pixel 2XL RSSI"
