esphome:
  name: soil1
  platform: esp32
  board: mhetesp32minikit

wifi:
  ssid: !secret network
  password: !secret wpa2

logger:

api:
  password: !secret basic

ota:
  password: !secret basic

# Cf. https://esphome.io/components/sensor/
sensor:
  - platform: adc
    pin: GPIO36
    name: "soil1_moisture"
    attenuation: 11db
    update_interval: 60s
    
    icon: "mdi:water-percent"
    unit_of_measurement: '%'
    accuracy_decimals: 1
    filters:
      # 1.1v = in water
      # 3.9v = dry
      lambda: |-
        return (3.9 - x) * 100.0 / (3.9 - 1.1);
