esphome:
  name: bme280${id}
  platform: esp32
  board: mhetesp32minikit

wifi:
  ssid: !secret network
  password: !secret wpa2

logger:

api:
  password: !secret basic

ota:
  password: !secret basic

i2c:

sensor:
  - platform: bme280
    temperature:
      name: "${friendly_name} Temperature"
      id: ${id}_temperature
      # filters:
      #   - sliding_window_moving_average:
      #       window_size: ${window_size}
      #       send_every: ${send_every}
    pressure:
      name: "${friendly_name} Pressure"
      id: ${id}_pressure
      # filters:
      #   - sliding_window_moving_average:
      #       window_size: ${window_size}
      #       send_every: ${send_every}
    humidity:
      name: "${friendly_name} Relative Humidity"
      id: ${id}_humidity
      # filters:
      #   - sliding_window_moving_average:
      #       window_size: ${window_size}
      #       send_every: ${send_every}
    address: 0x76
    iir_filter: 8x
    update_interval: ${update_interval}

  - platform: template
    id: ${id}_altitude
    name: "Altitude"
    update_interval: ${update_interval}
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(${id}_temperature).state + 273.15) / 0.0065) *
        (powf((STANDARD_SEA_LEVEL_PRESSURE / id(${id}_pressure).state), 0.190234) - 1); // in meter

  - platform: template
    id: ${id}_absolute_humidity
    name: "Absolute humidity"
    accuracy_decimals: 2
    update_interval: ${update_interval}
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(${id}_temperature).state) /
        (id(${id}_temperature).state + 243.5)) * id(${id}_humidity).state * mw) /
        ((273.15 + id(${id}_temperature).state) * r); // in grams/m^3

  - platform: template
    id: ${id}_sea_level_pressure
    name: "Equivalent sea level pressure"
    update_interval: ${update_interval}
    lambda: |-
      const float STANDARD_ALTITUDE = 0.6; // in meters, see note
      return id(${id}_pressure).state / powf(1 - ((0.0065 * STANDARD_ALTITUDE) /
        (id(${id}_temperature).state + (0.0065 * STANDARD_ALTITUDE) + 273.15)), 5.257); // in hPa
