esphome:
  name: esp32cam_${id}
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret network
  password: !secret wpa2

logger:

api:
  password: !secret basic

ota:
  password: !secret basic

# https://randomnerdtutorials.com/esp32-cam-video-streaming-face-recognition-arduino-ide/
# https://esphome.io/components/esp32_camera.html#configuration-variables
esp32_camera:
  name: ${friendly_name} Camera
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO17, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15
  resolution: 640x480
  jpeg_quality: 10
