# Cf. https://esphome.io/devices/sonoff.html
esphome:
  name: sonoff${id}
  platform: ESP8266
  #board: esp01_1m
  board: esp8285

wifi:
  ssid: !secret network
  password: !secret wpa2
  # # # Uncomment below to override IP address
  # # # Cf. https://esphome.io/components/wifi.html#manual-ips
  # manual_ip:
  #   static_ip: 192.168.86.210
  #   gateway: 192.168.86.1
  #   subnet: 255.255.255.0
  # power_save_mode: none  # light high

logger:

api:
  password: !secret basic

ota:
  password: !secret basic

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
