switch:
  - platform: gpio
    pin:
      number: ${gpio_pin}
      mode: OUTPUT
    id: ${id}

  - platform: template
    name: "${Friendly name}"
    icon: "mdi:${icon}"
    turn_on_action:
      - switch.turn_on: ${id}
      - delay: ${toggle_delay}
      - switch.turn_off: ${id}
      - delay: ${toggle_delay}
